version: 2.1

workflows:
  ci:
    jobs:
      - lint
      - typecheck:
          requires: [lint]
      - test:
          requires: [typecheck]
      - size:
          requires: [test]

jobs:
  base:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
      - run: npm install --no-audit --no-fund
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  lint:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
      - run: npm install --no-audit --no-fund
      - run: npm run lint

  typecheck:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
      - run: npm install --no-audit --no-fund
      - run: npm run typecheck

  test:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
      - run: npm install --no-audit --no-fund
      - run: npm run test:ci
      - store_artifacts:
          path: junit.xml
          when: always

  size:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
      - run: npm install --no-audit --no-fund
      - run: npm run size
