version: 2.1

workflows:
  ci:
    jobs:
      - lint
      - typecheck:
          requires: [lint]
      - test:
          requires: [typecheck]
      - size:
          requires: [test]

jobs:
  lint:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - run: npm install --no-audit --no-fund
      - run: npm run lint

  typecheck:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - run: npm install --no-audit --no-fund
      - run: npm run typecheck

  test:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - run: npm install --no-audit --no-fund
      - run: npm run test:ci
      - store_artifacts:
          path: junit.xml
          when: always

  size:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - run: npm install --no-audit --no-fund
      - run: npm run size
